#!/bin/bash  
#
#SBATCH -A scholar
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=32
#SBATCH --time=04:00:00
#SBATCH --job-name 2ito_large_vs_1
#SBATCH --error=%x-%J-%u.err
#SBATCH --output=%x-%J-%u.out
 
module load gcc/14.1.0
module load openmpi/5.0.5

mpirun -n 32 $DOCK_BASE_MPI/bin/dock6.mpi -i virtual_1.in -o virtual_1.out
